### PR TITLE
fix: add IAT Batches to populateHashes

### PR DESCRIPTION
**Pull request by Boettner-eric**
# Changes
- pre-populate IAT batch entries with ids based off of their hashes

# Why Are Changes Being Made
- normal ACH batches are pre-populated with ids in the `populateHashes` function
- the processing of IAT entries should be consistent with normal ACH batch entries

### CODE REVIEW

**Comment by wadearnold** [comment]
Can we get a test case to prove the new behavior?

**Comment by Boettner-eric** [comment]
Updated with a new test.

**Review by wadearnold — APPROVED** [review]
Can you merge this in @adamdecaf

**Comment by jasonbornsteinMOOV** [comment]
> Can you merge this in @adamdecaf

I can take care of it while @adamdecaf is out of the office

**Review by jasonbornsteinMOOV — APPROVED** [review]

**Comment by wadearnold** [comment]
I approved the change. I meant that someone needs to merge and cut a release.

**Pull request merged**
